### ISSUE TITLE
I get an error after enabling an Overview Panel on 2.3, 1.6.0

### ISSUE THREAD

**Issue by TheJester12** [symphonists/dashboard#10]
Symphony Warning: Invalid argument supplied for foreach()

An error occurred in /Applications/MAMP/htdocs/new-site/extensions/dashboard/extension.driver.php around line 489

484                 // tags request found
485                 if($repo_tags) {
486                     $repo_tags = json_decode($repo_tags);
487                     $tags = array();
488
489                     foreach($repo_tags->tags as $tag => $ref) {
490                         // remove tags that contain strings
491                         if(preg_match('/[a-zA]/i', $tag)) continue;
492                         $tags[] = $tag;
493                     }

**Comment by nitriques** [comment]
Fixed, so closing.
