### ISSUE TITLE
Dashboard and html pages

### ISSUE THREAD

**Issue by DaveRev** [symphonists/dashboard#14]
Hi Nick!
I install this extension on symphony 2.3.1 and I try to insert an "HTML block". For testing, I insert "www.facebook.com" in the url field, and a new panel with facebook is created. 
I know, it's a good idea, but I only try to do it!
Now I want to delete this panel, so I enabled changes and click on "modify" button.
When I click on it, a new page is opened (not with symphony styles) and there are all buttons to modify my panel, but if I try to delete this panel, nothing happens!!

**Comment by nitriques** [comment]
Old issue, closing. Please comment if the bug still exists.
