### ISSUE TITLE
Error when Github is offline

### ISSUE THREAD

**Issue by bernardodiasc** [symphonists/dashboard#15]
Hi Nick, today Github was offline, then I get an error on line 489 in `extension.driver.php` where `$repo_tags` arent `null`, because it have all 404 Gihtub html inside.

I've changed this line to `if(is_array($repo_tags)) {` and thats work fine. Check if this is a good solution please.

**Comment by nitriques** [comment]
It is ! please send a PR ! I'll wait before releasing 1.8.0 if you want to fix this as well. Thanks!
